# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56579da8669a26c62a322912d4e9a8a4620231a40efe54cc035672b7d3d36b5ecc72f4c952a49884a88ebf80159f0457392938ae93f8f6723579b4b51cb4c714

test:
  secret_key_base: 9e549cd9e72cfbad1e0a9b4ef4512c7517f7151c9c9bfc4e270ed867ff09cbd17a75db374780bc7ea4f53c711acc18d3844cd3c7286fc5a0c4e7c6392d22f084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
